"""
Django settings for proyecto project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import cloudinary
import cloudinary.uploader
import cloudinary.api
from pathlib import Path
import os

# URL a la que redirige @login_required si el usuario no está logueado
# ¡Asegúrate que apunte al nombre de TU url de login!


LOGIN_URL = 'loginUser'

# URL a la que redirige después de un LOGIN exitoso (si no se especifica 'next')
# ¡Asegúrate que apunte al nombre de TU url de perfil!
LOGIN_REDIRECT_URL = 'profileUser' # O 'perfil_usuario', el que estés usando

# URL a la que redirige después de un LOGOUT exitoso
# ¡ASEGÚRATE DE QUE ESTA LÍNEA EXISTA Y SEA CORRECTA!
LOGOUT_REDIRECT_URL = 'loginUser'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Puedes nombrar esta carpeta como quieras
oin(BASE_DIR, 'media')
# --- Usar Cloudinary como Almacenamiento por Defecto para Media ---
# Esto permite que models.ImageField funcione con Cloudinary
# --- Configuración de Cloudinary ---
# LEE DESDE LAS VARIABLES DE ENTORNO DE RENDER


cloudinary.config(
  cloud_name = 'dnuedvkia',
  api_key = '727868416774616',
  api_secret = 'ZsyQL2cXfWe6KNq_SAuzAmQJSeU', # Ahora usa las variables hardcoded
  secure = True
)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.j



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3##i+#9e^qlis_s!+*4@w7n72dzpf9rp1ozjdylr&d3@&9^(=3'

# SECURITY WING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['construccion-3lh4.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'construccion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.wlkuhjbpersxhfubomkd',
        'PASSWORD': 'asPB19510',
        'HOST': 'aws-0-us-east-2.pooler.supabase.com',
        'PORT': '6543',
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'construccion/static')]
# --- Usar Cloudinary como Almacenamiento por Defecto para Media ---
# Esto permite que models.ImageField funcione con Cloudinary




# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
